extends@: default

form:
  fields:
    tabs:
      fields:
        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    header.body_classes:
                      markdown: true
                      description: 'Page classes space separated'
        buttons:
          type: tab
          title: QBoss
          fields:
            qboss_style:
              type: section
              title: Style Options
              underline: true
            header.qboss_padding:
              type: select
              label: Top & Bottom Padding
              description: 'The top and bottom padding for this page content'
              size: medium
              default: md-pad
              options:
                no-pad: No padding
                xs-pad: Smaller (16px)
                sm-pad: Small (32px)
                md-pad: Midium (64px)
                lg-pad: Large (96px)
                xl-pad: Larger (128px)