extends@: default

form:
  fields:
    tabs:
      fields:
        content:
          fields:
            header.subtitle:
              type: text
              style: vertical
              label: Subtitle

        buttons:
          type: tab
          title: QBoss
          fields:
            columns:
              type: columns
              fields:
                column1:
                  type: column
                  fields:
                    qboss_layout:
                      type: section
                      title: Page/Module Layout
                      underline: true
                    header.show_module_heading:
                      type: toggle
                      label: Show Title & Subtitle
                      help: Controls whether the page/module Title and Subtitle are displayed or not.
                      highlight: 1
                      default: 1
                      options:
                        1: PLUGIN_ADMIN.ENABLED
                        0: PLUGIN_ADMIN.DISABLED
                      validate:
                        type: bool
                    header.show_page_header:
                      type: toggle
                      label: Show Header
                      help: Controls whether the page header is displayed or not.
                      highlight: 1
                      default: 1
                      options:
                        1: PLUGIN_ADMIN.ENABLED
                        0: PLUGIN_ADMIN.DISABLED
                      validate:
                        type: bool
                    header.show_page_footer:
                      type: toggle
                      label: Show Footer
                      help: Controls whether the page footer is displayed or not.
                      highlight: 1
                      default: 1
                      options:
                        1: PLUGIN_ADMIN.ENABLED
                        0: PLUGIN_ADMIN.DISABLED
                      validate:
                        type: bool
                column2:
                  type: column
                  fields:
                    qboss_style:
                      type: section
                      title: Page/Module Style
                      underline: true
                    header.modular_padding:
                      type: select
                      label: Top & Bottom Padding
                      description: 'The top and bottom padding for this page content'
                      size: medium
                      default: md-pad
                      options:
                        no-pad: No padding
                        xs-pad: Smaller (16px)
                        sm-pad: Small (32px)
                        md-pad: Midium (64px)
                        lg-pad: Large (96px)
                        xl-pad: Larger (128px)
            qboss_advanced:
              type: section
              title: Advanced Settings
              underline: true

              fields:
                header.modular_classes:
                  type: text
                  label: Modular CSS Classes
                  markdown: true
                  description: 'Modular classes space separated'
                header.modular_id:
                  type: text
                  size: small
                  label: Modular Element ID
                  description: 'The HTML element ID'
                  validate:
                    rule: slug
